name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Print system information
      run: |
        echo "OS: $(uname -a)"
        echo "Python: $(python --version)"
        echo "Pip: $(pip --version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov black ruff mypy
        python -m pip install -e .

    - name: Format and lint
      run: |
        black --check .
        ruff check .
        mypy plexomatic

    - name: Test with pytest
      run: |
        mkdir -p test_logs
        python -m pytest tests/ -v --cov=plexomatic | tee test_logs/pytest.log

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_logs
